name = "nssatools"
main = "worker.js"
compatibility_date = "2025-08-10"

[assets]
directory = "."
binding = "ASSETS"
exclude = [
  "**/node_modules/**",
  "**/.git/**",
  "**/.gitignore",
  "**/.DS_Store",
  "**/wrangler.toml",
  "**/wrangler.toml.bak",
  "**/*.bak",
  "**/*.sample",
  "**/package*.json",
  "**/.vscode/**",
  "**/.idea/**",
  "**/worker.js"
]

[vars]
# Firebase Web config for browser initialization (public)
FIREBASE_API_KEY = "AIzaSyAQVuM1XSbFw_x3IQ0ZV98XwCWGbgFhIGM"
FIREBASE_AUTH_DOMAIN = "n8n-project-460516.firebaseapp.com"
FIREBASE_PROJECT_ID = "n8n-project-460516"
FIREBASE_STORAGE_BUCKET = "n8n-project-460516.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "18068529376"
FIREBASE_APP_ID = "1:18068529376:web:d1fe5d7e4e53c2817a3085"

# Cookie/session settings
SESSION_COOKIE_NAME = "nssatools_session"
SESSION_MAX_AGE = "604800" # 7 days in seconds

# Paths that can bypass auth (login assets, config script)
AUTH_BYPASS = "/auth,/firebase-config.js,/auth/login,/auth/logout"

# Route binding to custom domain
workers_dev = false

[[routes]]
pattern = "tools.nssa.io/*"
zone_name = "nssa.io"
