name = "nssa-cron"
main = "worker.js"
compatibility_date = "2025-08-08"

# 环境变量配置
[vars]
FIREBASE_API_KEY = "AIzaSyAQVuM1XSbFw_x3IQ0ZV98XwCWGbgFhIGM"
FIREBASE_AUTH_DOMAIN = "n8n-project-460516.firebaseapp.com"
FIREBASE_PROJECT_ID = "n8n-project-460516"
FIREBASE_STORAGE_BUCKET = "n8n-project-460516.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "18068529376"
FIREBASE_APP_ID = "1:18068529376:web:d1fe5d7e4e53c2817a3085"

[[rules]]
type = "ESModule"
globs = ["worker.js"]